# Price Combinations
# Requirements: 
# Write a program which will process the data listed below. 
# The data must be placed into a csv file and read from it.
# The first line of the csv file is the target price and the following lines are menu items you could buy.
# The program should then find a combination of dishes that has a total of exactly the target price. If there is no solution found, then the program should print that there is no combination of dishes that is equal to the target price. 
# The program must run with different data files generated by us in the same format, so provide instructions on how to run the program from command line with command line parameters to read alternative input files.

# Here are some sample data values: 

# Target price, $15.05
# mixed fruit,$2.15
# french fries,$2.75
# side salad,$3.35
# hot wings,$3.55
# mozzarella sticks,$4.20
# sampler plate,$5.80


require 'csv'
p CSV.read("target_price.csv")[1]